CREATE TABLE "MBC"."MEMBER_3" 
   (   "ID" VARCHAR2(20 BYTE), 
   "PW" VARCHAR2(200 BYTE), 
   "NAME" VARCHAR2(20 BYTE), 
   "PHONE" VARCHAR2(20 BYTE), 
   "BIRTH" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE UNIQUE INDEX "MBC"."PK_MEMBER_3" ON "MBC"."MEMBER_3" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "MBC"."MEMBER_3" ADD CONSTRAINT "PK_MEMBER_3" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MBC"."MEMBER_3" MODIFY ("ID" NOT NULL ENABLE);


CREATE TABLE "MBC"."STORE_3" 
   (	"STORECODE" NUMBER(7,0), 
	"STORENAME" VARCHAR2(30 BYTE), 
	"STOREADDRESS" VARCHAR2(100 BYTE), 
	"STORECATEGORY" VARCHAR2(20 BYTE), 
	"STORELIKES" NUMBER(6,0) DEFAULT 0, 
	"STOREAREA" VARCHAR2(20 BYTE), 
	"STOREIMAGE" VARCHAR2(200 BYTE), 
	"PARKING" NUMBER(1,0) DEFAULT 0, 
	"LATITUDE" FLOAT(126),
	"LONGITUDE" FLOAT(126), 
	"STOREHOURS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "MBC"."STORE_3"."STORELIKES" IS '
';

  CREATE UNIQUE INDEX "MBC"."PK_STORE_3" ON "MBC"."STORE_3" ("STORECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "MBC"."STORE_3" ADD CONSTRAINT "PK_STORE_3" PRIMARY KEY ("STORECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MBC"."STORE_3" MODIFY ("PARKING" NOT NULL ENABLE);
  ALTER TABLE "MBC"."STORE_3" MODIFY ("STORECODE" NOT NULL ENABLE);


CREATE SEQUENCE booking_seq
START WITH 1
INCREMENT BY 1;

  CREATE TABLE "MBC"."BOOKING_3" 
   (   "TABLENUM" NUMBER(7,0), 
   "STORECODE" NUMBER(7,0), 
   "ID" VARCHAR2(20 BYTE), 
   "SARAMSU" NUMBER(3,0), 
   "STATE" VARCHAR2(20 BYTE), 
   "BOOKINGDATE" DATE, 
   "BOOKINGTIME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE UNIQUE INDEX "MBC"."PK_BOOKING_3" ON "MBC"."BOOKING_3" ("TABLENUM", "STORECODE", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "MBC"."BOOKING_3" ADD CONSTRAINT "PK_BOOKING_3" PRIMARY KEY ("TABLENUM", "STORECODE", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MBC"."BOOKING_3" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MBC"."BOOKING_3" MODIFY ("STORECODE" NOT NULL ENABLE);
  ALTER TABLE "MBC"."BOOKING_3" MODIFY ("TABLENUM" NOT NULL ENABLE);

  ALTER TABLE "MBC"."BOOKING_3" ADD CONSTRAINT "FK_MEMBER_3_TO_BOOKING_3_1" FOREIGN KEY ("ID")
     REFERENCES "MBC"."MEMBER_3" ("ID") ENABLE;
  ALTER TABLE "MBC"."BOOKING_3" ADD CONSTRAINT "FK_STORE_3_TO_BOOKING_3_1" FOREIGN KEY ("STORECODE")
     REFERENCES "MBC"."STORE_3" ("STORECODE") ENABLE;


  CREATE TABLE "MBC"."STORE_IMAGE_3" 
   (   "STORECODE" NUMBER(7,0), 
   "IMAGE_FILENAME" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "MBC"."STORE_IMAGE_3" MODIFY ("IMAGE_FILENAME" NOT NULL ENABLE);
  ALTER TABLE "MBC"."STORE_IMAGE_3" MODIFY ("STORECODE" NOT NULL ENABLE);


  CREATE TABLE "MBC"."REVIEW_3" 
   (   "ID" VARCHAR2(20 BYTE), 
   "STORECODE" NUMBER(7,0), 
   "CONTENT" VARCHAR2(200 BYTE), 
   "STARS" FLOAT(126), 
   "TITLE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE UNIQUE INDEX "MBC"."REVIEW_3_PK" ON "MBC"."REVIEW_3" ("ID", "STORECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "MBC"."REVIEW_3" ADD CONSTRAINT "REVIEW_3_PK" PRIMARY KEY ("ID", "STORECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

  ALTER TABLE "MBC"."REVIEW_3" MODIFY ("STORECODE" NOT NULL ENABLE);
  ALTER TABLE "MBC"."REVIEW_3" MODIFY ("ID" NOT NULL ENABLE);

  ALTER TABLE "MBC"."REVIEW_3" ADD CONSTRAINT "FK_MEMBER_3_TO_REVIEW_3_1" FOREIGN KEY ("ID")
     REFERENCES "MBC"."MEMBER_3" ("ID") ENABLE;


  CREATE TABLE "MBC"."MEMBER_LIKES" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"STORECODE" NUMBER(7,0), 
	"LIKED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE UNIQUE INDEX "MBC"."UNQ_MEMBER_STORE" ON "MBC"."MEMBER_LIKES" ("MEMBER_ID", "STORECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "MBC"."MEMBER_LIKES" ADD CONSTRAINT "UNQ_MEMBER_STORE" UNIQUE ("MEMBER_ID", "STORECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

  ALTER TABLE "MBC"."MEMBER_LIKES" ADD CONSTRAINT "FK_MEMBER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "MBC"."MEMBER_3" ("ID") ENABLE;
  ALTER TABLE "MBC"."MEMBER_LIKES" ADD CONSTRAINT "FK_STORE" FOREIGN KEY ("STORECODE")
	  REFERENCES "MBC"."STORE_3" ("STORECODE") ENABLE;


  CREATE SEQUENCE  "MBC"."FAQ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10200 CACHE 20 NOORDER  NOCYCLE ;

  CREATE TABLE "MBC"."FAQ_3" 
   (   "NUM" NUMBER(6,0), 
   "ID" VARCHAR2(20 BYTE), 
   "TITLE" VARCHAR2(50 BYTE), 
   "CONTENT" VARCHAR2(1000 BYTE), 
   "WDATE" DATE, 
   "STATE" VARCHAR2(20 BYTE), 
   "GROUPS" NUMBER(6,0), 
   "STEP" NUMBER(1,0), 
   "SECRET" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  CREATE UNIQUE INDEX "MBC"."FAQ_3_PK" ON "MBC"."FAQ_3" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  ALTER TABLE "MBC"."FAQ_3" ADD CONSTRAINT "FAQ_3_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "MBC"."FAQ_3" MODIFY ("NUM" NOT NULL ENABLE);